# Site Settings
title: "Professional Website"
description: "A modern, responsive website built with Jekyll and optimized for GitHub Pages"
url: "https://yourusername.github.io"
baseurl: "/repository-name"  # Change this to your repository name

# Author Information
author:
  name: "Your Name"
  email: "your.email@example.com"
  phone: "+1 (555) 123-4567"

# Build Settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Collections
collections:
  pages:
    output: true
    permalink: /:name/

# Default Layouts
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins (for GitHub Pages compatibility)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - .gitignore

# Include files that are normally excluded
include:
  - _pages

# Site Variables
theme: null
timezone: UTC

# Social Media Links (optional)
social:
  twitter: "yourtwitter"
  github: "yourgithub"
  linkedin: "yourlinkedin"

# Navigation
navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about"
  - title: "Services"
    url: "#services"
  - title: "Contact"
    url: "#contact"

# SEO Settings
seo:
  type: "WebSite"
  locale: "en_US"
